SMS/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls',namespace='facultyapp')),
    path('studentapp/', include('studentapp.urls',namespace='studentapp')),
]

facultyapp/urls.py
from django.urls import path, include
from . import views
app_name = 'facultyapp'
urlpatterns = [
    path('FacultyHomePage/', views.FacultyHomePage, name="FacultyHomePage"),
    path('add_course/', views.add_course, name="add_course"),
    path('view-student-list/', views.view_student_list, name='view_student_list'),
    path('post_marks/', views.post_marks, name='post_marks'),
    # path('marks_success/', views.marks_success, name='marks_success'),
]

studentapp/urls.py
from django.urls import path, include
from . import views
app_name = 'studentapp'
urlpatterns = [
    path('StudentHomePage/', views.StudentHomePage, name="StudentHomePage"),
    path('view_marks/', views.view_marks, name="view_marks"),

]

templates/Navbar/FacultyNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

   <style>
        /* Your custom styles go here */
        .navbar {
            font-size: 18px;
            color: white;  /* Adjust the font size as needed */
        }

        .navbar-brand,
        .navbar-nav .nav-link {
            font-size: 18px; /* Adjust the font size as needed */
            font-weight: bold;
            color: white;

        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg flex-shrink-3 py-sm-1" style="background-color:#341dca">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-weight: bold">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>

                  <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:add_course' %}">Add Course to Student</a>
        </li>
                            <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:view_student_list' %}">View Students List</a>
        </li>
                            <li class="nav-item">
          <a class="nav-link" href="{% url 'facultyapp:post_marks' %}">Post Marks</a>
        </li>
      </ul>
    </div>

        <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>
      </ul>

  </div>
</nav>
{% block body %}

{% endblock %}
<footer id ="sticky-footer" class="flex-shrink-0 py-sm-1">
  <div class = "container text-center">
    <small> Copyright &copy; Dr. Deepak. V - K L University. All rights reserved</small>
  </div>
</footer>
<style>
  #sticky-footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: #046A38;
    color: white;
    font-weight: bold;
  }
</style>
</body>
</html>

templates/Navbar/ProjectNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

   <style>
        /* Your custom styles go here */
        .navbar {
            font-size: 18px;
            color: white;  /* Adjust the font size as needed */
        }

        .navbar-brand,
        .navbar-nav .nav-link {
            font-size: 18px; /* Adjust the font size as needed */
            font-weight: bold;
            color: white;

        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg flex-shrink-3 py-sm-1" style="background-color:#d65353">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-weight: bold">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
            <li><a class="dropdown-item" href="{% url 'exceptionpagecall' %}">Exception Handling</a></li>
            <li><a class="dropdown-item" href="{% url 'randompagecall' %}">OTP Generator</a></li>
            <li><a class="dropdown-item" href="{% url 'add_task' %}">TO DO App</a></li>
            <li><a class="dropdown-item" href="{% url 'calculatorpagecall' %}">Calculator App</a></li>
            <li><a class="dropdown-item" href="{% url 'datetimepagecall' %}">Date Calculator</a></li>
            <li><a class="dropdown-item" href="{% url 'timezonepagecall' %}">Time App</a></li>
            <li><a class="dropdown-item" href="{% url 'upload_file' %}">Generate Graph</a></li>
            <li><a class="dropdown-item" href="{% url 'contact_list' %}">Contact Manager</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>

          </ul>
        </li>
                  <li class="nav-item">
          <a class="nav-link" href="{% url 'add_student' %}">Add Students</a>
        </li>
                            <li class="nav-item">
          <a class="nav-link" href="{% url 'student_list' %}">View Students List</a>
        </li>
      </ul>
    </div>

    <ul  class="navbar-nav ms-auto">

        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}


      </ul>

  </div>
</nav>
{% block body %}

{% endblock %}
<footer id ="sticky-footer" class="flex-shrink-0 py-sm-1">
  <div class = "container text-center">
    <small> Copyright &copy; Dr. Deepak. V - K L University. All rights reserved</small>
  </div>
</footer>
<style>
  #sticky-footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: #046A38;
    color: white;
    font-weight: bold;
  }
</style>
</body>
</html>

templates/Navbar/StudentNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

   <style>
        /* Your custom styles go here */
        .navbar {
            font-size: 18px;
            color: white;  /* Adjust the font size as needed */
        }

        .navbar-brand,
        .navbar-nav .nav-link {
            font-size: 18px; /* Adjust the font size as needed */
            font-weight: bold;
            color: white;

        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg flex-shrink-3 py-sm-1" style="background-color:#4e8a27">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent" style="font-weight: bold">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>


          <li class="nav-item">
          <a class="nav-link" href="#">View Attendance</a>
        </li>
                    <li class="nav-item">
          <a class="nav-link" href="{% url 'studentapp:view_marks' %}">View Marks</a>
        </li>
      </ul>
    </div>

        <ul  class="navbar-nav ms-auto">
<li>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
                <li class="nav-item">
          <a class="nav-link" href="{% url 'UserRegisterPageCall' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLoginPageCall' %}">Login</a>
        </li>
        {% endif %}

 </li>
      </ul>

  </div>
</nav>
{% block body %}

{% endblock %}
<footer id ="sticky-footer" class="flex-shrink-0 py-sm-1">
  <div class = "container text-center">
    <small> Copyright &copy; Dr. Deepak. V - K L University. All rights reserved</small>
  </div>
</footer>
<style>
  #sticky-footer {
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: #046A38;
    color: white;
    font-weight: bold;
  }
</style>
</body>
</html>